
document.write("<header>"
+ "        <h1>PXF 2.0.1.0</h1>"
+ "        <p>Prototype PXF extensions for HAWQ</p>"
+ "        <p class=\"view\"><a href=\"https://github.com/Pivotal-Field-Engineering/pxf-field\">View the Project on GitHub <small>Pivotal-Field-Engineering/pxf-field</small></a></p>"
+ "        <ul>"
+ "          <li><a href=\"https://github.com/Pivotal-Field-Engineering/pxf-field/zipball/master\">Download <strong>ZIP File</strong></a></li>"
+ "          <li><a href=\"https://github.com/Pivotal-Field-Engineering/pxf-field/tarball/master\">Download <strong>TAR Ball</strong></a></li>"
+ "          <li><a href=\"https://github.com/Pivotal-Field-Engineering/pxf-field\">View On <strong>GitHub</strong></a></li>"
+ "        </ul>"
+ "		<br/><br/>"        
+ "		<p><a href=\"index.html\">Home</a><br/>"
+ "		<br/>"
+ "		Getting Started<br/>"
+ "		<a href=\"installing.html\">Installing an Extension</a><br/>"
+ "		<a href=\"developing.html\">Developing and Testing Extensions</a><br/>"
+ "		<a href=\"versioning.html\">Extension Versioning</a><br/>"
+ "		<a href=\"apidocs/index.html?com/pivotal/pxf/PxfUnit.html\" target=\"_blank\">PXF Unit JavaDoc</a><br/>"
+ "		<br/>"
+ "		Prototype Extensions<br/>"
+ "		<a href=\"accumulo.html\">Accumulo</a><br/>"
+ "		<a href=\"cassandra.html\">Cassandra</a><br/>"
+ "		<a href=\"json.html\">JSON</a><br/>"
+ "		<a href=\"pxf-pipes.html\">Pipes</a><br/>"
+ "		<a href=\"redis.html\">Redis</a><br/>"
+ "		</p>"		
+ "      </header>");
